import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import type {
  ChatEvent,
  ApprovalRequest,
  HealthSubitem,
  HealthStatus,
  AuthorizedDir,
  WorkspaceEntry,
  SkillSummary,
  SubagentConfig,
  SubagentsConfig,
  TeamSubagentsConfig,
  CustomSubagentEntry,
  CustomSubagentsMap,
  CustomSubagentInput,
  ToolsConfig,
  SkillFileInfo,
  ThreadInfo,
  ProfileCategory,
  ProfileEntry,
  ProfileEntryRequest,
  ModelEntry,
  ModelProviderId,
  ModelTestRequest,
  ModelTestResponse,
  McpServerConfig,
  McpServerStatus,
  McpTransport,
  McpToolInfo,
  McpTestResult,
} from "../../shared/api-types";

export type {
  ChatEvent,
  ApprovalRequest,
  HealthSubitem,
  HealthStatus,
  AuthorizedDir,
  WorkspaceEntry,
  SkillSummary,
  SubagentConfig,
  SubagentsConfig,
  TeamSubagentsConfig,
  CustomSubagentEntry,
  CustomSubagentsMap,
  CustomSubagentInput,
  ToolsConfig,
  SkillFileInfo,
  ThreadInfo,
  ProfileCategory,
  ProfileEntry,
  ProfileEntryRequest,
  ModelEntry,
  ModelProviderId,
  ModelTestRequest,
  ModelTestResponse,
  McpServerConfig,
  McpServerStatus,
  McpTransport,
  McpToolInfo,
  McpTestResult,
};

export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
